# Generated by Django 3.2.4 on 2021-07-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=50)),
                ('area', models.CharField(choices=[('Bashundhara', 'Bashundhara'), ('Gulshan', 'Gulshan'), ('Mirpur', 'Mirpur'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Wari', 'Wari'), ('Jatrabri', 'Jatrabri'), ('Gulishtan', 'Gulishtan'), ('Khulshi', 'Khulshi'), ('GEC', 'GEC'), ('Lalkhan Bazar', 'Lalkhan Bazar'), ('Dewan Hat', 'Dewan Hat'), ('Agrabad', 'Agrabad'), ('2no Gate', '2no Gate'), ('Muradpur', 'Muradpur'), ('Bahaddarhat', 'Bahaddarhat'), ('Wasa', 'Wasa'), ('Katghar', 'Katghar')], max_length=50)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Rice', 'Rice'), ('Fish', 'Fish'), ('Oil', 'Oil'), ('Vegetables', 'Vegetables'), ('Beverages', 'Beverages'), ('Meat', 'Meat'), ('Bakery & Snacks', 'Bakery & Snacks'), ('Dairy', 'Dairy')], max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
